version: '3'

services:
  app:
    image: adhocore/lemp
    # For different app you can use different names. (eg: )
    container_name: fcctpbot
    volumes:
      # app source code
      - ./:/var/www/html
      # db data persistence
      - db_data:/var/lib/mysql
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 8884:80
      - 3313:3306
    environment:
      DISABLE: ${DISABLE}
      MYSQL_ROOT_PASSWORD: '1234567890'
      MYSQL_DATABASE: fctpbotdb
      MYSQL_USER: fccbotusr
      MYSQL_PASSWORD: '12456'
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix

    command: /bin/sh -c "chmod -R 775 /var/www/html/storage && chown -R www-data:www-data /var/www/html/storage && supervisord -n && npm run dev && git config --global user.email 'joseluishube@gmail.com' && git config --global user.name 'José Luis H'"
volumes:
  db_data: {}
